<?php
/**
 * @file
 * Code for the WYSIWYG starter feature.
 */

include_once 'wysiwyg_starter.features.inc';

/**
 * Implements hook_wysiwyg_plugin().
 */
function wysiwyg_starter_wysiwyg_plugin($editor, $version) {
  if ($editor == 'ckeditor') {
    return array(
      'codemirror' => array(
         'extensions' => array('codemirror' => t('CodeMirror')),
         'path' => wysiwyg_get_path('ckeditor_plugins') . '/codemirror',
         'internal' => FALSE,
         'load' => TRUE,
      ),
    );
  }
}
