<?php 

/**
 * Implementation of hook_wysiwyg_plugin().
 */
function wysiwyg_mediaembed_wysiwyg_plugin($editor, $version) {
  switch ($editor) {
   case 'ckeditor':
      return array(
        'mediaembed' => array(
          'buttons' => array(
             'MediaEmbed' => 'Media Embed',
          ),
          'path' => drupal_get_path('module', 'wysiwyg_mediaembed') . '/plugin/mediaembed/',
          'url' => 'http://ckeditor.com/addon/mediaembed',
          'load' => TRUE,
        ),
      );
  }
}
